### PR TITLE
Add support for ES2022 class fields and private methods.

### PR DESCRIPTION
**Pull request by sanex3339**

### CODE REVIEW

**Comment by sanex3339** [comment]
@Constellation @michaelficarra let's do this fast this year

**Comment by sanex3339** [comment]
@Constellation @michaelficarra ping

**Comment by sanex3339** [comment]
This feature is now available in https://www.npmjs.com/package/@javascript-obfuscator/estraverse

**Comment by connor4312** [comment]
We hit this in the VS Code debugger in https://github.com/microsoft/vscode-js-debug/issues/1113. Would be great to see it merged!

**Comment by robpalme** [comment]
Is there any way people could help to get this merged?  I think various people might be able to assist if someone could enumerate the remaining work here.

**Review by michaelficarra — APPROVED** [review]

**Pull request merged**
