### PR TITLE
Support MetaProperty

### PR DESCRIPTION
**Pull request by twada**
Add support for MetaProperty defined in [The ESTree Spec](https://github.com/estree/estree/blob/master/es6.md#metaproperty).

related:
 - [MetaProperty](https://github.com/estree/estree/blob/master/es6.md#metaproperty)
 - [A new ES6 draft is available](https://mail.mozilla.org/pipermail/es-discuss/2015-January/041072.html)
 - [Classes in ECMAScript 6 (final semantics)](http://www.2ality.com/2015/02/es6-classes-final.html)

### CODE REVIEW

**Comment by twada** [comment]
@michaelficarra Thanks!

**Comment by twada** [comment]
@Constellation would you cut a new release soon? (maybe a minor bump?)

**Comment by Constellation** [comment]
OK, I'll release it with major bumps.

**Comment by twada** [comment]
@Constellation Thanks!!

**Pull request merged**
