### PR TITLE
Added support for ChainExpression node

### PR DESCRIPTION
**Pull request by sanex3339**
Added support for ChainExpression node

### CODE REVIEW

**Comment by sanex3339** [comment]
@michaelficarra please check this.

**Comment by sanex3339** [comment]
@michaelficarra please check this.

**Comment by dilame** [comment]
Hi guys! This PR is very important for me and many people on the world! Please, merge it

**Comment by sanex3339** [comment]
@michaelficarra re-ping

**Comment by bricss** [comment]
Can anyone just force merge it, eventually?

**Comment by michaelficarra** [comment]
@bricss No, that's not how this works.

**Comment by sanex3339** [comment]
@michaelficarra  What are we waiting for?

**Comment by bricss** [comment]
That's the only thing which is blocking **ESLint** from getting [optional chaining support](https://github.com/eslint/eslint/pull/13416) so far 😬

**Comment by sanex3339** [comment]
@michaelficarra ping

**Comment by sanex3339** [comment]
Ping

**Comment by sanex3339** [comment]
Hi. Thank you!

**Comment by michaelficarra** [comment]
Released `5.2.0`.

**Pull request merged**
