### PR TITLE
Add support for BooleanLiteral, RegExpLiteral, NumericLiteral, String…

### PR DESCRIPTION
**Pull request by thelordoftheboards**
I noticed that estraverse does not work with the latest version of babylon from babel 6. The issue is because of:

The Literal node type has been unoverloaded and split into BooleanLiteral, RegExpLiteral, NumericLiteral, StringLiteral and NullLiteral.

( https://github.com/babel/babel/blob/master/CHANGELOG.md#600 ).

I added the definitions above to the same places in estraverse as Literal was, without removing Literal itself. Here is a small test script that works with the change, and breaks without it:

-----
const babylon = require("babylon"); //import babylon from 'babylon'; <-- does not work with import
import generate from 'babel-generator';
//import estraverse from 'estraverse'; // From npm
import estraverse from './../estraverse/estraverse/estraverse.js'; // My local project with change

let code = "'string' + 12345"

let ast = babylon.parse( code, {
  sourceType: "script",
  plugins: [ ],
  presets: [ ]
} );

console.log( '----- input code:' )
console.log( code )

// The example does not really matter here, it either returns the original code, or breaks
let result = estraverse.replace( ast.program, {
    enter: function (node) {
      // Not really doing anything, just an example
    }
});

console.log( '----- Result JSON:' )
console.log( JSON.stringify( result ) );

console.log( '----- Result generated code:' )
console.log( generate( result ).code );
-----

I am not sure if babylon support is amongst the goals for estraverse, and I do not understand the architecture of estraverse enough to be able to tell if the changes I made are appropriate. However, they seem to work so I figured out I will share.

### CODE REVIEW

**Comment by twada** [comment]
@thelordoftheboards You can traverse/replace non-standard AST Nodes [by adding `keys` to visitor](https://github.com/estools/estraverse#example-usage), not by modifying estraverse.

```js
let result = estraverse.replace( ast.program, {
    keys: require("babel-types").VISITOR_KEYS,
    enter: function (node) {
        // Not really doing anything, just an example
    }
});
```

**Comment by thelordoftheboards** [comment]
Thank you. I did not know that. Appreciated.
Please excuse my ignorance I am barely learning how to use the stuff.

On Wed, Nov 25, 2015 at 7:05 PM, Takuto Wada <notifications@github.com>
wrote:

> @thelordoftheboards <https://github.com/thelordoftheboards> You can
> traverse/replace non-standard AST Nodes by adding keys to visitor
> <https://github.com/estools/estraverse#example-usage>, not by modifying
> estraverse.
>
> let result = estraverse.replace( ast.program, {
>     keys: require("babel-types").VISITOR_KEYS,
>     enter: function (node) {
>         // Not really doing anything, just an example
>     }
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/estools/estraverse/pull/62#issuecomment-159790546>.
>



-- 
--
Aleksandar Chalakov
Code Foundries, CTO
www.codefoundries.com
(949) 742-4387

**Comment by twada** [comment]
@thelordoftheboards No problem at all!
This is a good hint for README improvement ;)

**Comment by thelordoftheboards** [comment]
Hey, something good will come out of it after all :) Thank you again and
have a good day!

On Wed, Nov 25, 2015 at 7:12 PM, Takuto Wada <notifications@github.com>
wrote:

> @thelordoftheboards <https://github.com/thelordoftheboards> No problem at
> all!
> This is a good hint for README improvement ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/estools/estraverse/pull/62#issuecomment-159791200>.
>



-- 
--
Aleksandar Chalakov
Code Foundries, CTO
www.codefoundries.com
(949) 742-4387

**Pull request closed without merging**
